### ISSUE TITLE
How it works in background ?

### ISSUE THREAD

**Issue by LiangyongFShen** [zwopple/PocketSocket#45]
I use the framework to develop a IM app, but when the app enter background, it can not receive messages! What should I do?

**Comment by robertjpayne** [comment]
@LiangyongFShen we don't make any assumptions about backgrounding or activity. If you're developing a chat application I strongly recommend you implement the background activity API's or use push notifications to wake up the app and resume the socket connection.

Alternatively you can use the VOIP flag on the stream but you'd need to fork PocketSocket and set that yourself. It's not something we really are targeting since a WebSocket isn't normally VOIP.

**Comment by LiangyongFShen** [comment]
Thanks a lot ! 
Are that any blogs about setting  VOIP flag on the stream ?

**Comment by robertjpayne** [comment]
@LiangyongFShen you normally have to be a Voice Over IP phone calling app to get that background activity entitlement through Apple App Review.

`NSStreamNetworkServiceTypeVoIP` is the flag you have to set on the stream, again you'll have to fork PocketSocket as you'll need to configure the stream.

Alternatively you can just use the PSWebSocketDriver and BYO networking.
